# Generated by Django 4.2 on 2023-06-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertising',
            old_name='client_id',
            new_name='client',
        ),
    ]
